import { redirect } from "next/navigation"
import { currentUser } from "@clerk/nextjs"

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await currentUser()

  if (user) {
    redirect("/app/wardrobe")
  }

  return (
    <div>
      {/* Generated by https://bg.ibelick.com/ */}
      {/* eslint-disable-next-line tailwindcss/no-contradicting-classname */}
      <div className="absolute inset-0 -z-10 size-full bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem]">
        <div className="absolute inset-0 bg-[radial-gradient(circle_800px_at_100%_200px,#d5c5ff,transparent)]"></div>
      </div>
      <main className="flex w-full flex-col items-center justify-center">
        {children}
      </main>
    </div>
  )
}
